# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "selectable_attr_rails"
  s.version = "0.3.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Takeshi Akima"]
  s.date = "2011-11-03"
  s.description = "selectable_attr_rails makes possible to use selectable_attr in rails application"
  s.email = "akm2000@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "gemfiles/Gemfile.rails-2.3.14",
    "gemfiles/Gemfile.rails-3.0.10",
    "gemfiles/Gemfile.rails-3.1.1",
    "init.rb",
    "install.rb",
    "lib/selectable_attr_i18n.rb",
    "lib/selectable_attr_rails.rb",
    "lib/selectable_attr_rails/db_loadable.rb",
    "lib/selectable_attr_rails/helpers.rb",
    "lib/selectable_attr_rails/helpers/abstract_selection_helper.rb",
    "lib/selectable_attr_rails/helpers/check_box_group_helper.rb",
    "lib/selectable_attr_rails/helpers/radio_button_group_helper.rb",
    "lib/selectable_attr_rails/helpers/select_helper.rb",
    "lib/selectable_attr_rails/validatable.rb",
    "lib/selectable_attr_rails/validatable/base.rb",
    "lib/selectable_attr_rails/validatable/enum.rb",
    "lib/selectable_attr_rails/version.rb",
    "selectable_attr_rails.gemspec",
    "spec/database.yml",
    "spec/fixtures/.gitignore",
    "spec/introduction_spec.rb",
    "spec/schema.rb",
    "spec/selectable_attr_i18n_spec.rb",
    "spec/spec_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/akm/selectable_attr_rails/"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "selectable_attr_rails makes possible to use selectable_attr in rails application"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.14"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.14"])
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.14"])
      s.add_runtime_dependency(%q<selectable_attr>, [">= 0.3.15"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.18"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5.3"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<rdiscount>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.14"])
      s.add_dependency(%q<activerecord>, [">= 2.3.14"])
      s.add_dependency(%q<actionpack>, [">= 2.3.14"])
      s.add_dependency(%q<selectable_attr>, [">= 0.3.15"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<yard>, ["~> 0.7.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.18"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, ["~> 0.5.3"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.14"])
    s.add_dependency(%q<activerecord>, [">= 2.3.14"])
    s.add_dependency(%q<actionpack>, [">= 2.3.14"])
    s.add_dependency(%q<selectable_attr>, [">= 0.3.15"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<yard>, ["~> 0.7.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.18"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, ["~> 0.5.3"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
  end
end

